export type RecipeSourceKey = 'default' | 'product' | 'profile' | 'metric' | 'canvas' | 'points'

const lines = (...values: string[]) => values.join('\n')

export const recipeSources: Record<RecipeSourceKey, string> = {
  default: lines(
    "import { MotionStage, cardsRenderer } from '@itagan/spatial-motion'",
    '',
    'const stage = new MotionStage({',
    '  container,',
    '  renderer: cardsRenderer({',
    '    aspectRatio: 1,',
    "    style: { shape: 'circle', borderWidth: 2, borderColor: '#67e8f9' },",
    '    resolveStyle(item) {',
    '      return item.meta?.featured',
    "        ? { borderColor: '#facc15', borderWidth: 4 }",
    '        : undefined',
    '    },',
    '  }),',
    '})',
  ),
  product: lines(
    "import { defineCardTemplate, html } from '@itagan/spatial-motion/card-template'",
    '',
    'const content = defineCardTemplate<{ price: number }>(',
    '  (item, { formatNumber, when }) => html`',
    '    <div class="product">',
    '      ${when(item.image, () => html`',
    '        <img src=${item.image} style="height:62%;object-fit:cover" />',
    '      `)}',
    '      <span class="title">${item.title}</span>',
    '      <span class="price">¥${formatNumber(item.meta?.price ?? 0)}</span>',
    '    </div>',
    '  `,',
    '  {',
    '    styles: {',
    '      product: {',
    "        display: 'flex',",
    "        flexDirection: 'column',",
    '        padding: 5,',
    '        gap: 4,',
    "        background: 'linear-gradient(135deg, #3b1029, #be123c)',",
    "        overflow: 'hidden',",
    '      },',
    "      title: { fontSize: 10, fontWeight: 700, lineClamp: 1, textAlign: 'center' },",
    "      price: { color: '#ffe4e6', fontSize: 9, fontWeight: 700, textAlign: 'center' },",
    '    },',
    '  },',
    ')',
    '',
    'new MotionStage({ container, renderer: cardsRenderer({ content }) })',
  ),
  profile: lines(
    "import { defineCardTemplate, html } from '@itagan/spatial-motion/card-template'",
    '',
    'const content = defineCardTemplate<{ role: string }>(',
    '  item => html`',
    '    <div class="profile">',
    '      <img src=${item.image} style="height:68%;object-fit:cover" />',
    '      <span class="name">${item.title}</span>',
    '      <span class="role">${item.meta?.role}</span>',
    '    </div>',
    '  `,',
    '  {',
    '    styles: {',
    '      profile: {',
    "        display: 'flex',",
    "        flexDirection: 'column',",
    '        padding: 5,',
    '        gap: 3,',
    "        background: 'linear-gradient(145deg, #083344, #155e75)',",
    '      },',
    "      name: { fontSize: 10, fontWeight: 700, lineClamp: 1, textAlign: 'center' },",
    "      role: { color: '#a5f3fc', fontSize: 8, lineClamp: 1, textAlign: 'center' },",
    '    },',
    '  },',
    ')',
    '',
    'new MotionStage({ container, renderer: cardsRenderer({ aspectRatio: 0.75, content }) })',
  ),
  metric: lines(
    "import { defineCardTemplate, html } from '@itagan/spatial-motion/card-template'",
    '',
    'const content = defineCardTemplate<{ score: number }>(',
    '  item => html`',
    '    <div class="metric">',
    '      <span class="label">${item.title}</span>',
    '      <span class="score">${item.meta?.score}</span>',
    '      <span class="unit">ENGAGEMENT</span>',
    '    </div>',
    '  `,',
    '  {',
    '    styles: {',
    '      metric: {',
    "        display: 'flex',",
    "        flexDirection: 'column',",
    "        justifyContent: 'center',",
    "        alignItems: 'center',",
    "        background: 'linear-gradient(120deg, #1e1b4b, #6d28d9)',",
    '      },',
    "      score: { color: '#fff', fontSize: 18, fontWeight: 800 },",
    '    },',
    '  },',
    ')',
    '',
    'new MotionStage({ container, renderer: cardsRenderer({ aspectRatio: 16 / 9, content }) })',
  ),
  canvas: lines(
    "import { MotionStage, cardsRenderer } from '@itagan/spatial-motion'",
    '',
    'const stage = new MotionStage({',
    '  container,',
    '  renderer: cardsRenderer({',
    '    aspectRatio: 16 / 9,',
    '    async draw(context, item, bounds, resolvedStyle) {',
    '    const gradient = context.createLinearGradient(',
    '      bounds.x, bounds.y, bounds.x + bounds.width, bounds.y,',
    '    )',
    "    gradient.addColorStop(0, '#1e1b4b')",
    "    gradient.addColorStop(1, '#6d28d9')",
    '    context.fillStyle = gradient',
    '    context.fillRect(bounds.x, bounds.y, bounds.width, bounds.height)',
    '',
    "    context.fillStyle = '#fff'",
    "    context.font = '800 18px sans-serif'",
    "    context.textAlign = 'center'",
    '    context.fillText(',
    '      String(item.meta?.score ?? 0),',
    '      bounds.x + bounds.width / 2,',
    '      bounds.y + bounds.height / 2,',
    '    )',
    '    },',
    '  }),',
    '})',
  ),
  points: lines(
    "import { MotionStage } from '@itagan/spatial-motion/core'",
    "import { sphere } from '@itagan/spatial-motion/layouts/sphere'",
    "import { pointsRenderer } from '@itagan/spatial-motion/renderers/points'",
    '',
    'const stage = new MotionStage({',
    '  container,',
    "  quality: 'high',",
    '  renderer: pointsRenderer({',
    '      size: 0.72,',
    '      resolveColor(item, index) {',
    "        if (item.meta?.featured) return '#facc15'",
    '        return `hsl(${index * 47 % 360} 72% 58%)`',
    '      },',
    '  }),',
    '})',
    '',
    'await stage.setItems(items)',
    'await stage.to(sphere({ fit: \'contain\' }), { duration: 0 })',
  ),
}
